; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./
include_dir = Core\Inc

[env:genericSTM32F411CE]
platform = ststm32
board = genericSTM32F411CE
upload_protocol = stlink
board_build.startup_src = ""
build_flags = 
	-Wl,-Map,${BUILD_DIR}/firmware.map  ; <-- FORCE MAP FILE GENERATION
	-ICore/Inc
	-IDrivers/CMSIS/Include
	-IDrivers/CMSIS/Device/ST/STM32F4xx/Include
	-IDrivers/STM32F4xx_HAL_Driver/Inc
	-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy
	-DSTM32F411xE

; 2. Dynamically compile the source code inside the Drivers directory 
lib_extra_dirs = Drivers

build_src_filter =
    -<*>
	+<Core/Src/>
	+<Drivers/STM32F4xx_HAL_Driver/Src/>
;	+<startup_stm32f411xe.S>
;    +<../Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c>
;    +<../Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f411xe.s>

board_build.ldscript = PIO_STM32F411xx_FLASH.ld

; --- Serial Monitor Configuration ---
monitor_speed = 9600 ; Must match the baud rate in your code
monitor_parity=N
monitor_rts=0
monitor_dtr=0
monitor_filters = send_on_enter
monitor_echo = yes

debug_tool = stlink